### ISSUE TITLE
Use Pinner service to optimise boot

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_msm8916-common#1]
https://review.lineageos.org/#/c/165648/2/overlay/frameworks/base/core/res/res/values/config.xml

**Comment by minz1** [comment]
https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/fc2c8e1c2f09705c32ffbc326cb2be54a878f545
https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/aa0c97898509b5075c1ad7e239c7f0c4aee683de

Done here, will test soon.
