### ISSUE TITLE
Clean up unneeded adreno firmware

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_msm8916-common#13]
Remove unneeded adreno firmware from proprietary-files.txt and from vendor blobs (+PR to Muppets and associated commit to gerrit)

**Comment by minz1** [comment]
Should be done; I need a tester

**Comment by vzvikaramba** [comment]
@minz1 I tested leaving just the a300* and a400* files, works fine.
