### ISSUE TITLE
cmhw: Swithch to MDNIE Color Calibration system

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_device_samsung_msm8916-common#14]
I guess we're need to change color calibration cmhw

https://github.com/LineageOS/android_device_samsung_hero-common/commit/3b8e7ffccd9dacfa51df80b02d4daf3ceac2de98

**Comment by vzvikaramba** [comment]
@vlw You would have to check if the kernel supports it first

**Comment by vlw** [comment]
@vince2678 Almost all Samsung kernels supports MDNIE. This kernel supports too. But anyway we're need to test this file

**Comment by minz1** [comment]
@vlw I think we do have support for it. I can look into it.

**Comment by minz1** [comment]
@minz1 I am wrong, I don't think we have MDNIE support

**Comment by vzvikaramba** [comment]
@minz1 I checked the sysfs path, it looks like the interface exists, so maybe it works

**Comment by minz1** [comment]
@vince2678 I just checked the sysfs path as well, and I haven't seen it

**Comment by vzvikaramba** [comment]
@minz1 /sys/class/mdnie/mdnie/sensorRGB ?

**Comment by minz1** [comment]
@vince2678 yes, that path does not exist

**Comment by vzvikaramba** [comment]
It exists on mine, so maybe it's display driver specific. @vlw, go ahead and add the cmhw in a test branch, and if it's tested and fine, put it in the main branch.

**Comment by vzvikaramba** [comment]
@vlw , can you test the class on cm-14.1-mdnie branch and see if it works fine.

**Comment by vzvikaramba** [comment]
Closing since there has been no assignment, and no progress made on this

**Comment by therootlord** [comment]
@vince2678 ive tested it, working fine for me (j5xnlte)

**Comment by vzvikaramba** [comment]
@therootlord This commit https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/5774d2edf0121b6b0c0d99d26da56c77d0f4939b ?

**Comment by therootlord** [comment]
@vince2678 yes

**Comment by vzvikaramba** [comment]
@therootlord can you post a screenshot of the mdnie config screen in Settings

**Comment by therootlord** [comment]
@vince2678 
![screenshot_20170821-003113](https://user-images.githubusercontent.com/16946825/29502716-6b00e5f0-8608-11e7-8187-3adc834d7dfd.png)
![screenshot_20170821-003120](https://user-images.githubusercontent.com/16946825/29502717-6b013aaa-8608-11e7-927a-9e43f0ff8e15.png)
![screenshot_20170821-003132](https://user-images.githubusercontent.com/16946825/29502718-6b0a5f86-8608-11e7-85e3-bbd2566c7c29.png)

here, the screen color didnt change on the pic but on device it changes

**Comment by vzvikaramba** [comment]
@therootlord That doesn't look any different from the normal color calibration system
