### ISSUE TITLE
config: wifi: wpa_supplicant.conf build

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_device_samsung_msm8916-common#15]
wpa_supplicant.conf can be made from sources

# WPA supplicant
PRODUCT_PACKAGES += \
    wpa_supplicant.conf

**Comment by vzvikaramba** [comment]
@vlw Where is the source file located in the build directory structure?

**Comment by minz1** [comment]
For now, I'm going to close this, since the only type of file I can find is an example configuration
