### ISSUE TITLE
cmhw: add keydisabler

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_device_samsung_msm8916-common#16]

**Comment by minz1** [comment]
https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/de0775ec586457ca41a9b2ff74fc2e4b042e08fb

**Comment by vzvikaramba** [comment]
The commit is incomplete. Could it be removed from the main branch and put in another branch for now until the kernel side interface is complete?

**Comment by vzvikaramba** [comment]
@vlw  can you test the key disabler cmhw class. If the settings appear but the touch keys aren't disabled, I may need to invert the logic in setActive().

**Comment by vzvikaramba** [comment]
Tested and done.
