### ISSUE TITLE
add liblights with BLN support

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_device_samsung_msm8916-common#17]
also we're need to check hardware/samsung, maybe it is already exists and need to do nothing

**Comment by vlw** [comment]
l8r we're need to add BLN kernel support

**Comment by vzvikaramba** [comment]
@vlw liblights provided by qcom source (hardware/qcom). We don't really need a custom one anyways since none of the devices have colour or notification leds

**Comment by vzvikaramba** [comment]
@vlw What is BLN?

**Comment by vlw** [comment]
BlinkLightNotification

**Comment by vlw** [comment]
Use buttons light as notification led

**Comment by vzvikaramba** [comment]
@vlw Do any of our devices even have backlit buttons?

**Comment by vlw** [comment]
A series have

**Comment by vzvikaramba** [comment]
Check if the qcom lights hal doesn't already have that feature at hardware/qcom

**Comment by vlw** [comment]
I find it https://github.com/LineageOS/android_hardware_samsung/commit/87346837214e2fa327b5563ee4a0d4f60a52b781

**Comment by vzvikaramba** [comment]
@vlw Check hardware/qcom because that's the liblights used by the msm8916-common tree

**Comment by vzvikaramba** [comment]
@vlw If it doesn't, we can switch to the samsung one if they are comparable on all the other things

**Comment by vlw** [comment]
https://github.com/LineageOS/android_hardware_samsung/commit/df15802d15796cd3439af80b010cfab60a66d1b5

**Comment by vlw** [comment]
we're need to use Samsung one

**Comment by vzvikaramba** [comment]
@vlw Does your device have the appropriate sysfs interface (/sys/class/misc/backlightnotification/notification_led) ?

**Comment by vlw** [comment]
this interface will exists after adding BLN driver into the kernel

**Comment by vzvikaramba** [comment]
@vlw Well, then you need to make an issue for that first

**Comment by vlw** [comment]
@vince2678 yeah, I'm go ahead

**Comment by vzvikaramba** [comment]
A device specific one for a3 was created.
