### ISSUE TITLE
libril-shim

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_device_samsung_msm8916-common#19]
I guess we're need to add ril-shim building

**Comment by vzvikaramba** [comment]
@vlw ril shim already exists. Please check in msm8916-common for anything else before opening more issues

**Comment by vlw** [comment]
it exists but not building

**Comment by vlw** [comment]
need to add smth like this
PRODUCT_PACKAGES += \
    libril_shim

**Comment by vzvikaramba** [comment]
@vlw The device-common tree is the one that needs to specify that, since not all the rils are pre-MM

**Comment by vlw** [comment]
okay

**Comment by vlw** [comment]
but in ramdisk hardcoded use this lib
export LD_SHIM_LIBS /system/lib/libril.so|libril_shim.so
nope if this lib willn't exists?

**Comment by vzvikaramba** [comment]
@vlw If it doesn't exist, then the shim command is ignored
