### ISSUE TITLE
Rewrite msm8916 sepolicies

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_msm8916-common#27]
The branch `cm-14.1-sepolicy` is specifically for that.

**Comment by vince2678** [comment]
List of denials:

denied  { open } for  pid=499 comm="wcnss_service" path="/efs/wifi/.mac.info" dev="mmcblk0p13" ino=22 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { getattr } for  pid=499 comm="wcnss_service" path="/efs/wifi/.mac.info" dev="mmcblk0p13" ino=22 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { search } for  pid=499 comm="wcnss_service" name="wifi" dev="mmcblk0p13" ino=18 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=1
denied  { read } for  pid=499 comm="wcnss_service" name=".mac.info" dev="mmcblk0p13" ino=22 scontext=u:r:wcnss_service:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1

denied  { getattr } for  pid=3214 comm="dboxed_process0" path="/data/data/com.android.chrome" dev="mmcblk0p27" ino=49578 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=1
denied  { getattr } for  pid=6271 comm="dboxed_process0" path="/data/data/com.android.chrome" dev="mmcblk0p27" ino=49578 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=1

denied  { create } for  pid=493 comm="init" name="rild-cas" scontext=u:r:init:s0 tcontext=u:object_r:socket_device:s0 tclass=sock_file permissive=1
denied  { write } for  pid=493 comm="init" name="rild-cas" dev="tmpfs" ino=3597 scontext=u:r:init:s0 tcontext=u:object_r:socket_device:s0 tclass=sock_file permissive=1
denied  { setattr } for  pid=493 comm="init" name="rild-cas" dev="tmpfs" ino=3597 scontext=u:r:init:s0 tcontext=u:object_r:socket_device:s0 tclass=sock_file permissive=1

denied  { dac_override } for  pid=474 comm="rmt_storage" capability=1  scontext=u:r:rmt_storage:s0 tcontext=u:r:rmt_storage:s0 tclass=capability permissive=1
denied  { write } for  pid=462 comm="rfs_access" name="rfsa" dev="debugfs" ino=8389 scontext=u:r:rfs_access:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
denied  { write open } for  pid=462 comm="rfs_access" path="/sys/kernel/debug/rmt_storage/rfsa" dev="debugfs" ino=8389 scontext=u:r:rfs_access:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
denied  { net_raw } for  pid=462 comm="rfs_access" capability=13  scontext=u:r:rfs_access:s0 tcontext=u:r:rfs_access:s0 tclass=capability permissive=1
denied  { net_raw } for  pid=474 comm="rmt_storage" capability=13  scontext=u:r:rmt_storage:s0 tcontext=u:r:rmt_storage:s0 tclass=capability permissive=1

denied  { dac_read_search } for  pid=1569 comm="rild" capability=2  scontext=u:r:rild:s0 tcontext=u:r:rild:s0 tclass=capability permissive=1
denied  { dac_read_search } for  pid=493 comm="rild" capability=2  scontext=u:r:rild:s0 tcontext=u:r:rild:s0 tclass=capability permissive=1
denied  { dac_read_search } for  pid=727 comm="rild" capability=2  scontext=u:r:rild:s0 tcontext=u:r:rild:s0 tclass=capability permissive=1


denied  { open } for  pid=463 comm="sh" path="/system/etc/init.qcom.bt.sh" dev="mmcblk0p25" ino=16245 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:bluetooth_loader_exec:s0 tclass=file permissive=1
denied  { read } for  pid=463 comm="sh" name="init.qcom.bt.sh" dev="mmcblk0p25" ino=16245 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:bluetooth_loader_exec:s0 tclass=file permissive=1


denied  { execute } for  pid=463 comm="sh" name="btnvtool" dev="mmcblk0p25" ino=56025 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1
denied  { execute_no_trans } for  pid=584 comm="sh" path="/system/bin/btnvtool" dev="mmcblk0p25" ino=56025 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1
denied  { getattr } for  pid=463 comm="sh" path="/system/bin/btnvtool" dev="mmcblk0p25" ino=56025 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1

denied  { read } for  pid=1569 comm="rild" name="telephony.db" dev="mmcblk0p27" ino=40808 scontext=u:r:rild:s0 tcontext=u:object_r:radio_data_file:s0 tclass=lnk_file permissive=1
denied  { search } for  pid=1569 comm="rild" name="imei" dev="mmcblk0p13" ino=23 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=1

denied  { getattr } for  pid=1569 comm="rild" path="/efs/FactoryApp/keystr" dev="mmcblk0p13" ino=42 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { read } for  pid=1569 comm="rild" name="keystr" dev="mmcblk0p13" ino=42 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { open } for  pid=1569 comm="rild" path="/efs/FactoryApp/keystr" dev="mmcblk0p13" ino=42 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1


denied  { open } for  pid=1569 comm="rild" path="/efs/imei/mps_code.dat" dev="mmcblk0p13" ino=24 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { getattr } for  pid=1569 comm="rild" path="/efs/imei/mps_code.dat" dev="mmcblk0p13" ino=24 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1
denied  { read } for  pid=1569 comm="rild" name="mps_code.dat" dev="mmcblk0p13" ino=24 scontext=u:r:rild:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=1


denied  { getattr } for  pid=1359 comm="system_server" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { getattr } for  pid=1715 comm="WifiStateMachin" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { getattr } for  pid=1732 comm="Binder:1359_3" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { getattr } for  pid=2413 comm="Binder:1359_6" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { getattr } for  pid=2464 comm="Binder:1359_8" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { open } for  pid=1715 comm="WifiStateMachin" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { open } for  pid=1732 comm="Binder:1359_3" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { open } for  pid=2413 comm="Binder:1359_6" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { write } for  pid=1359 comm="system_server" name="powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { write } for  pid=1715 comm="WifiStateMachin" name="powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { write } for  pid=1732 comm="Binder:1359_3" name="powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { write } for  pid=2413 comm="Binder:1359_6" name="powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { write } for  pid=2464 comm="Binder:1359_8" name="powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { open } for  pid=1359 comm="system_server" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1
denied  { open } for  pid=2464 comm="Binder:1359_8" path="/persist/alarm/powerOffAlarmSet" dev="mmcblk0p22" ino=32 scontext=u:r:system_server:s0 tcontext=u:object_r:persist_file:s0 tclass=file permissive=1


denied  { read open } for  pid=584 comm="sh" path="/system/bin/btnvtool" dev="mmcblk0p25" ino=56025 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1
denied  { getattr } for  pid=584 comm="btnvtool" path="/persist/.bt_nv.bin" dev="mmcblk0p22" ino=16 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:bluetooth_data_file:s0 tclass=file permissive=1


denied  { getattr } for  pid=837 comm="Binder:536_1" path="/firmware/image/widevine.mdt" dev="mmcblk0p1" ino=6986 scontext=u:r:mediadrmserver:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
denied  { open } for  pid=837 comm="Binder:536_1" path="/firmware/image/widevine.mdt" dev="mmcblk0p1" ino=6986 scontext=u:r:mediadrmserver:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
denied  { read } for  pid=837 comm="Binder:536_1" name="widevine.mdt" dev="mmcblk0p1" ino=6986 scontext=u:r:mediadrmserver:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
denied  { search } for  pid=837 comm="Binder:536_1" name="/" dev="mmcblk0p1" ino=1 scontext=u:r:mediadrmserver:s0 tcontext=u:object_r:firmware_file:s0 tclass=dir permissive=1


denied  { ioctl } for  pid=245 comm="e2fsck" path="/dev/block/mmcblk0p13" dev="tmpfs" ino=8861 ioctlcmd=127c scontext=u:r:fsck:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
denied  { open } for  pid=245 comm="e2fsck" path="/dev/block/mmcblk0p13" dev="tmpfs" ino=8861 scontext=u:r:fsck:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
denied  { read } for  pid=245 comm="e2fsck" name="mmcblk0p13" dev="tmpfs" ino=8861 scontext=u:r:fsck:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1
denied  { write } for  pid=245 comm="e2fsck" name="mmcblk0p13" dev="tmpfs" ino=8861 scontext=u:r:fsck:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1


denied  { getattr } for  pid=779 comm="chown" path="/data/data/com.android.providers.telephony/databases/HbpcdLookup.db" dev="mmcblk0p27" ino=40806 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:radio_data_file:s0 tclass=lnk_file permissive=1
denied  { read } for  pid=492 comm="sh" name="HbpcdLookup.db" dev="mmcblk0p27" ino=40806 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:radio_data_file:s0 tclass=lnk_file permissive=1
denied  { read } for  pid=779 comm="chown" name="HbpcdLookup.db" dev="mmcblk0p27" ino=40806 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:radio_data_file:s0 tclass=lnk_file permissive=1
denied  { setattr } for  pid=779 comm="chown" name="HbpcdLookup.db" dev="mmcblk0p27" ino=40806 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:radio_data_file:s0 tclass=lnk_file permissive=1


denied  { search } for  pid=3214 comm="dboxed_process0" name="tmp" dev="mmcblk0p27" ino=155042 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=1
denied  { search } for  pid=6271 comm="dboxed_process0" name="tmp" dev="mmcblk0p27" ino=155042 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=1


denied  { write } for  pid=484 comm="mm-qcamera-daem" name="/" dev="mmcblk0p27" ino=2 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1


denied  { write } for  pid=727 comm="rild" name="accept_ra_defrtr" dev="proc" ino=15070 scontext=u:r:rild:s0 tcontext=u:object_r:proc_net:s0 tclass=file permissive=1

**Comment by gerrit-galaxy-msm8916** [comment]
Done.
