### ISSUE TITLE
hwcomposer module not found

### ISSUE THREAD

**Issue by VirsysElectron** [Galaxy-MSM8916/android_device_samsung_msm8916-common#34]
I used this common tree in conjunction with your gt510wifi and gte-common tree to create an android build. It's an android 7.1.2 RR build without root. The hwcomposer driver (hwcomposer.msm8916.so) is in the system/lib/hw folder. The two gralloc drivers (which seem to be working) are in the same directory as the hwcomposer driver. I picked the hwcomposer from a working rom, it is definitely a working driver.

---- SurfaceFlinger log ----
11-20 13:26:58.464  1319  1319 I SurfaceFlinger: SurfaceFlinger is starting
11-20 13:26:58.466  1319  1319 I SurfaceFlinger: SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
11-20 13:26:58.468  1319  1319 D libEGL  : loaded /vendor/lib/egl/libEGL_adreno.so
11-20 13:26:58.493  1319  1319 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
11-20 13:26:58.518  1319  1319 D libEGL  : loaded /vendor/lib/egl/libGLESv2_adreno.so
11-20 13:26:58.537  1319  1319 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_64_LA.BR.1.2.9_RB1__release_AU (I38fdb1353f)
11-20 13:26:58.537  1319  1319 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
11-20 13:26:58.537  1319  1319 I Adreno-EGL: Build Date: 10/24/16 Mon
11-20 13:26:58.537  1319  1319 I Adreno-EGL: Local Branch: mybranch22985090
11-20 13:26:58.537  1319  1319 I Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.8
11-20 13:26:58.537  1319  1319 I Adreno-EGL: Local Patches: NONE
11-20 13:26:58.537  1319  1319 I Adreno-EGL: Reconstruct Branch: NOTHING
11-20 13:26:58.540  1319  1319 I gralloc : using (fd=12)
11-20 13:26:58.540  1319  1319 I gralloc : id           = mdssfb_80000
11-20 13:26:58.540  1319  1319 I gralloc : xres         = 768 px
11-20 13:26:58.540  1319  1319 I gralloc : yres         = 1024 px
11-20 13:26:58.540  1319  1319 I gralloc : xres_virtual = 768 px
11-20 13:26:58.540  1319  1319 I gralloc : yres_virtual = 2048 px
11-20 13:26:58.540  1319  1319 I gralloc : bpp          = 32
11-20 13:26:58.540  1319  1319 I gralloc : r            =  0:8
11-20 13:26:58.540  1319  1319 I gralloc : g            =  8:8
11-20 13:26:58.540  1319  1319 I gralloc : b            = 16:8
11-20 13:26:58.540  1319  1319 I gralloc : width        = 148 mm (131.805405 dpi)
11-20 13:26:58.540  1319  1319 I gralloc : height       = 197 mm (132.028427 dpi)
11-20 13:26:58.540  1319  1319 I gralloc : refresh rate = 2.31 Hz
**11-20 13:26:58.544  1319  1319 E SurfaceFlinger: hwcomposer module not found**
11-20 13:26:58.548  1319  1319 I SurfaceFlinger: EGL information:
11-20 13:26:58.548  1319  1319 I SurfaceFlinger: vendor    : Android
11-20 13:26:58.548  1319  1319 I SurfaceFlinger: version   : 1.4 Android META-EGL
11-20 13:26:58.548  1319  1319 I SurfaceFlinger: extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_create_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_KHR_image EGL_KHR_image_base EGL_KHR_lock_surface EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buff11-20 13:26:58.548  1319  1319 I SurfaceFlinger: Client API: OpenGL_ES
11-20 13:26:58.548  1319  1319 I SurfaceFlinger: EGLSurface: 8-8-8-8, config=0x5
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: OpenGL ES informations:
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: vendor    : Qualcomm
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: renderer  : Adreno (TM) 306
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: version   : OpenGL ES 3.0 V@145.0 AU@ (GIT@I38fdb1353f)
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: extensions: GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precis11-20 13:26:58.549  1319  1319 I SurfaceFlinger: GL_MAX_TEXTURE_SIZE = 4096
11-20 13:26:58.549  1319  1319 I SurfaceFlinger: GL_MAX_VIEWPORT_DIMS = 4096
11-20 13:26:58.556  1319  1319 I SurfaceFlinger: EGL information:
11-20 13:26:58.556  1319  1319 I SurfaceFlinger: vendor    : Android
11-20 13:26:58.556  1319  1319 I SurfaceFlinger: version   : 1.4 Android META-EGL
11-20 13:26:58.556  1319  1319 I SurfaceFlinger: extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_create_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_KHR_image EGL_KHR_image_base EGL_KHR_lock_surface EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buff11-20 13:26:58.556  1319  1319 I SurfaceFlinger: Client API: OpenGL_ES
11-20 13:26:58.556  1319  1319 I SurfaceFlinger: EGLSurface: 8-8-8-8, config=0x5

**Comment by vlw** [comment]
Send full logcat

20 февр. 2018 г. 21:57 пользователь "VirsysElectron" <
notifications@github.com> написал:

**Comment by VirsysElectron** [comment]
Whoops..
Tested the build again on my device this morning.
Logcat: https://pastebin.com/JAirxwSx

**Comment by vlw** [comment]
@VirsysElectron Looks like u can't read log. It is keystore issue, not audio.

**Comment by VirsysElectron** [comment]
I edited my comment already, I was in a hurry.
The keystore crashed, that's right.
Fixed it by deleting keystore.default and keystore.msm8916 like described [there](https://github.com/Galaxy-MSM8916/android_device_samsung_gprimeltezt/issues/1).
I'm always there for testing new variants of these two files.

**Comment by vzvikaramba** [comment]
Solved.

**Comment by vlw** [comment]
@vince2678 lol, use software keystore is not right way to fix
