### ISSUE TITLE
Write custom AudioHAL based on qcom HAL

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_msm8916-common#4]

**Comment by vzvikaramba** [comment]
Write custom oss hal, with in call audio working (God knows how this can be done).

**Comment by minz1** [comment]
This doesn't seem feasible at all, based on the results so far.

**Comment by vzvikaramba** [comment]
Yeah, the best bet at this point would be getting the oss ril to work. That seems like less of an uphill battle.

**Comment by minz1** [comment]
Same topic as issue #21 I guess
