### ISSUE TITLE
[MSM-8916 > Releases] The "Releases" page requires a restructuring, or the return / launch of a page where the builds are organized.

### ISSUE THREAD

**Issue by Beatz106** [Galaxy-MSM8916/android_device_samsung_msm8916-common#48]
Currently there are the main problems:

> By accessing https://github.com/Galaxy-MSM8916/releases/releases No release has a change log, it is through a file, which is something different, yes, no one can distinguish such changes.

![Screenshot_20201202-175136_Iceraven](https://user-images.githubusercontent.com/74375581/100946426-eda43f80-34c8-11eb-91ac-7b53242a28b4.png)

> Unlike: https://github.com/fork-maintainers/iceraven-browser/releases where if there is a changelog per release

![Screenshot_20201202-180051_Iceraven](https://user-images.githubusercontent.com/74375581/100946470-044a9680-34c9-11eb-9b6a-88846fa43ea8.png)

, here There is also no way to send any issue or error report, since the button does not exist.

![Screenshot_20201202-180127_Iceraven](https://user-images.githubusercontent.com/74375581/100946499-162c3980-34c9-11eb-845f-0e84d7f6ec0d.png)

> None of the builds can be tested for different problems, the most common being errors in the typical "updater-script" file. Moderators are required to discard or approve a new build

From the mobile version it is impossible to go immediately to the last existing compilation, in fact you have to navigate page by page until you reach the desired file, another problem is that they are out of order (if you want to find a build of LineageOS 17 for Grand Prime, you have to check the file name one by one)

**Comment by vzvikaramba** [comment]
@Beatz106 download.msm8916.com is the front-end for releases on github. An alternate release page is available at https://sourceforge.net/projects/galaxy-msm8916/files/, though it will only contain the most recent releases.
